# Generated by Django 2.1.2 on 2018-10-09 08:04

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(
                    max_length=128,
                    primary_key=True,
                    serialize=False
                )),
                ('owner', models.CharField(max_length=256)),
                ('balance', models.DecimalField(
                    decimal_places=2,
                    default=0.0,
                    max_digits=16
                )),
                ('currency', models.CharField(
                    choices=[
                        (
                            payments.models.Currencies('US Dollar'),
                            'US Dollar'
                        ),
                        (
                            payments.models.Currencies('Phillipine Peso'),
                            'Phillipine Peso'
                        ),
                        (
                            payments.models.Currencies('Russian Rouble'),
                            'Russian Rouble'
                        )
                    ],
                    max_length=128
                )),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('direction', models.CharField(
                    choices=[
                        (
                            payments.models.PaymentDirections('outgoing'),
                            'outgoing'
                        ),
                        (
                            payments.models.PaymentDirections('incoming'),
                            'incoming'
                        )
                    ],
                    max_length=128
                )),
                ('amount', models.DecimalField(
                    decimal_places=2,
                    max_digits=16,
                )),
                ('account', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='account',
                    to='payments.Account'
                )),
                ('from_account', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='from_account',
                    to='payments.Account'
                )),
                ('to_account', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='to_account',
                    to='payments.Account'
                )),
            ],
        ),
    ]
