# Generated by Django 2.1.2 on 2018-10-09 11:05

from django.db import migrations
from payments.models import Account, Currencies, send_transaction


def create_accounts(apps, schema_editor):
    Account.objects.create(
        id='alice_account',
        owner='alice',
        balance=125,
        currency=Currencies.PHP.name,
    )

    Account.objects.create(
        id='bob_account',
        owner='bob',
        balance=75,
        currency=Currencies.PHP.name,
    )


def create_payments(apps, schema_editor):
    send_transaction('alice_account', 'bob_account', 25)


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_accounts),
        migrations.RunPython(create_payments),
    ]
